<!DOCTYPE html>
<html lang="fr">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Gym</title>
    <link
      href="https://kit-free.fontawesome.com/releases/latest/css/free.min.css"
      rel="stylesheet" />
    <link
      href="https://fonts.googleapis.com/css2?family=Rubik:wght@300;400;500;700;900&display=swap"
      rel="stylesheet" />
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/styles.css" />
  </head>
  <body>
    <!----------------- HEADER -------------------------->
    <header>
      <div class="menu-desktop">
        <nav>
          <ul id="menu">
            <li>
              <a href ="<?= $requestUrl ?>/">
                <img src="<?= $wwwUrl ?>/img/logo.svg" class="logo" alt />
              </a>
            </li>
            <li>
              <a href ="<?= $requestUrl ?>/courses">cours collectif
              </a>
            </li>
            <li>
              <a href ="<?= $requestUrl ?>/booking">abonnement
              </a>
            </li>
            <li>
              <a href ="<?= $requestUrl ?>/session">séance à la carte
              </a>
            </li>
            <li>
              <a href ="<?= $requestUrl ?>/coaching">coaching
              </a>
            </li>
            <li>
              <a href ="<?= $requestUrl ?>/app">Gym app
              </a>
            </li>
            <li>
              <i class="fas fa-user"></i>
              <ul>
                <li>
                  <?php if(array_key_exists('user', $_SESSION)) {?>
                    <a href="<?= $requestUrl ?>/user/profil">Mon profil</a>
                    <?php if($_SESSION['user']['role'] == 'admin') {?>
                      <a href="<?= $requestUrl ?>/admin">Admin</a>
                    <?php } ?>
                      <a href="<?= $requestUrl ?>/user/logout">Déconnexion</a>
                  <?php } else {?>
                    <a href="<?= $requestUrl ?>/user/login">Se connecter</a>
                    <a href="<?= $requestUrl ?>/user/register">S'enregistrer</a>
                  <?php } ?>
                </li>
              </ul>
            </li>
          <ul>
        </nav>
      </div>
      <div class="menu-collapsed">
        <div class="bar"></div>
        <nav>
          <ul>
            <li>
              <?php if(array_key_exists('user', $_SESSION)) {?>
                <a href="<?= $requestUrl ?>/user/profil">Mon profil</a>
              <?php if($_SESSION['user']['role'] == 'admin') {?>
                <a href="<?= $requestUrl ?>/admin">Admin</a>
              <?php } ?>
                <a href="<?= $requestUrl ?>/user/logout">Déconnexion</a>
              <?php } else {?>
                <a href="<?= $requestUrl ?>/user/login">Connexion</a>
                <a href="<?= $requestUrl ?>/user/register">S'enregistrer</a>
              <?php } ?>
            </li>
            <li>
              <a href ="<?= $requestUrl ?>/courses">cours collectif
              </a>
            </li>
            <li>
              <a href ="<?= $requestUrl ?>/booking">abonnement
              </a>
            </li>
            <li>
              <a href ="<?= $requestUrl ?>/session">séance à la carte
              </a>
            </li>
            <li>
              <a href ="<?= $requestUrl ?>/coaching">coaching
              </a>
            </li>
            <li>
              <a href ="<?= $requestUrl ?>/app">app
              </a>
            </li>
          <ul>
        </nav>
      </div>
    </header>

    <!-- Affichage du template lié à la vue -->
    <?php include $this->viewData['template']; ?>

    <!----------------- FOOTER -------------------------->
    <footer class="black">
      <nav>
        <a href="<?= $requestUrl ?>/">accueil</a>
        <a href="<?= $requestUrl ?>/courses">cours collectifs</a>
        <a href="<?= $requestUrl ?>/coaching">coaching</a>
        <a href="<?= $requestUrl ?>/booking">abonnement</a>
        <a href="<?= $requestUrl ?>/subscription">séance à la carte</a>
        <a href="<?= $requestUrl ?>/app">gym app</a>
      </nav>
      <div>
        &copy; Gym 2020
      </div>
    </footer>

    <script
      src="https://code.jquery.com/jquery-3.5.1.min.js"
      integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0="
      crossorigin="anonymous"
    ></script>
    <script src="<?= $wwwUrl ?>/js/main.js"></script>
    <script src="<?= $wwwUrl ?>/js/utilities.js"></script>
  </body>
</html>
