  <body id="black">
    <!----------------- MAIN ---------------------------->
    <main>
      <section class="activities">
        <h1>Cours collectifs</h1>
        <section>
          <figure id="activity-bodybalance" class="courses">
            <img
              class="activity-bodybalance_picture"
              src="<?= $wwwUrl ?>/img/activities-body-balance-nb.jpg"
              alt=""
            />
            <figcaption class="activity-legend alternative">
              <h3>Body balance</h3>
              <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quibusdam quae illum ratione commodi sit tempora voluptatum rerum error, iste numquam placeat est inventore. Molestiae architecto doloremque neque nihil soluta animi quasi qui id aliquid consequatur. Sint laudantium optio itaque neque voluptates! Ex, aspernatur quod deleniti incidunt repellat aliquid repudiandae distinctio ipsum dolor, sit amet consectetur adipisicing elit. Quibusdam quae illum ratione commodi sit tempora voluptatum rerum error, iste numquam placeat est inventore. Molestiae architecto doloremque neque nihil soluta animi q?</p>
            </figcaption>
          </figure>
          <figure id="activity-bodypump" class="courses reverse bgbodypump">
            <img
              class="activity-bodypump_picture"
              src="<?= $wwwUrl ?>/img/activities-body-pump-nb.jpg"
              alt=""
            />
            <figcaption class="activity-legend alternative">
              <h3>Body pump</h3>
              <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quibusdam quae illum ratione commodi sit tempora voluptatum rerum error, iste numquam placeat est inventore. Molestiae architecto doloremque neque nihil soluta animi quasi qui id aliquid consequatur. Sint laudantium optio itaque neque voluptates! Ex, aspernatur quod deleniti incidunt repellat aliquid repudiandae distinctio ipsum dolor, sit amet consectetur adipisicing elit. Quibusdam quae illum ratione commodi sit tempora voluptatum rerum error, iste numquam placeat est inventore. Molestiae architecto doloremque neque nihil soluta animi q?</p>
            </figcaption>
          </figure>
          <figure id="activity-abdos" class="courses">
            <img
              class="activity-abdos_picture"
              src="<?= $wwwUrl ?>/img/activities-cuisse-abdos-fessiers-nb.jpg"
              alt=""
            />
            <figcaption class="activity-legend alternative">
              <h3>Abdos fessiers</h3>
              <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quibusdam quae illum ratione commodi sit tempora voluptatum rerum error, iste numquam placeat est inventore. Molestiae architecto doloremque neque nihil soluta animi quasi qui id aliquid consequatur. Sint laudantium optio itaque neque voluptates! Ex, aspernatur quod deleniti incidunt repellat aliquid repudiandae distinctio ipsum dolor, sit amet consectetur adipisicing elit. Quibusdam quae illum ratione commodi sit tempora voluptatum rerum error, iste numquam placeat est inventore. Molestiae architecto doloremque neque nihil soluta animi q?</p>
            </figcaption>
          </figure>
          <figure id="activity-fullbody" class="courses reverse">
            <img
              class="activity-fullbody_picture"
              src="<?= $wwwUrl ?>/img/activities-full-body-nb.jpg"
              alt=""
            />
            <figcaption class="activity-legend alternative">
              <h3>Full body</h3>
              <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quibusdam quae illum ratione commodi sit tempora voluptatum rerum error, iste numquam placeat est inventore. Molestiae architecto doloremque neque nihil soluta animi quasi qui id aliquid consequatur. Sint laudantium optio itaque neque voluptates! Ex, aspernatur quod deleniti incidunt repellat aliquid repudiandae distinctio ipsum dolor, sit amet consectetur adipisicing elit. Quibusdam quae illum ratione commodi sit tempora voluptatum rerum error, iste numquam placeat est inventore. Molestiae architecto doloremque neque nihil soluta animi q?</p>
            </figcaption>
          </figure>
          <figure id="activity-cardio" class="courses">
            <img
              class="activity-cardio_picture"
              src="<?= $wwwUrl ?>/img/activities-cardio-cycling-nb.jpg"
              alt=""
            />
            <figcaption class="activity-legend alternative">
              <h3>Cardio training</h3>
              <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quibusdam quae illum ratione commodi sit tempora voluptatum rerum error, iste numquam placeat est inventore. Molestiae architecto doloremque neque nihil soluta animi quasi qui id aliquid consequatur. Sint laudantium optio itaque neque voluptates! Ex, aspernatur quod deleniti incidunt repellat aliquid repudiandae distinctio ipsum dolor, sit amet consectetur adipisicing elit. Quibusdam quae illum ratione commodi sit tempora voluptatum rerum error, iste numquam placeat est inventore. Molestiae architecto doloremque neque nihil soluta animi q?</p>
            </figcaption>
          </figure>
          <figure id="activity-yoga" class="courses reverse">
            <img
              class="activity-yoga_picture"
              src="<?= $wwwUrl ?>/img/activities-yoga-nb.jpg"
              alt=""
            />
            <figcaption class="activity-legend alternative">
              <h3>Yoga</h3>
              <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quibusdam quae illum ratione commodi sit tempora voluptatum rerum error, iste numquam placeat est inventore. Molestiae architecto doloremque neque nihil soluta animi quasi qui id aliquid consequatur. Sint laudantium optio itaque neque voluptates! Ex, aspernatur quod deleniti incidunt repellat aliquid repudiandae distinctio ipsum dolor, sit amet consectetur adipisicing elit. Quibusdam quae illum ratione commodi sit tempora voluptatum rerum error, iste numquam placeat est inventore. Molestiae architecto doloremque neque nihil soluta animi q?</p>
            </figcaption>
          </figure>
          <figure id="activity-postural" class="courses">
            <img
              class="activity-postural_picture"
              src="<?= $wwwUrl ?>/img/activities-postural-ball-nb.jpg"
              alt=""
            />
            <figcaption class="activity-legend alternative">
              <h3>Postural ball</h3>
              <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quibusdam quae illum ratione commodi sit tempora voluptatum rerum error, iste numquam placeat est inventore. Molestiae architecto doloremque neque nihil soluta animi quasi qui id aliquid consequatur. Sint laudantium optio itaque neque voluptates! Ex, aspernatur quod deleniti incidunt repellat aliquid repudiandae distinctio ipsum dolor, sit amet consectetur adipisicing elit. Quibusdam quae illum ratione commodi sit tempora voluptatum rerum error, iste numquam placeat est inventore. Molestiae architecto doloremque neque nihil soluta animi q?</p>
            </figcaption>
          </figure>
          <figure id="activity-circuit" class="courses reverse">
            <img
              class="activity-circuit_picture"
              src="<?= $wwwUrl ?>/img/activities-circuit-training-nb.jpg"
              alt=""
            />
            <figcaption class="activity-legend alternative">
              <h3>Circuit training</h3>
              <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quibusdam quae illum ratione commodi sit tempora voluptatum rerum error, iste numquam placeat est inventore. Molestiae architecto doloremque neque nihil soluta animi quasi qui id aliquid consequatur. Sint laudantium optio itaque neque voluptates! Ex, aspernatur quod deleniti incidunt repellat aliquid repudiandae distinctio ipsum dolor, sit amet consectetur adipisicing elit. Quibusdam quae illum ratione commodi sit tempora voluptatum rerum error, iste numquam placeat est inventore. Molestiae architecto doloremque neque nihil soluta animi q?</p>
            </figcaption>
          </figure>
          <figure id="activity-crossfit" class="courses">
            <img
              class="activity-crossfit_picture"
              src="<?= $wwwUrl ?>/img/activities-crossfit-nb.jpg"
              alt=""
            />
            <figcaption class="activity-legend alternative">
              <h3>Crossfit</h3>
              <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quibusdam quae illum ratione commodi sit tempora voluptatum rerum error, iste numquam placeat est inventore. Molestiae architecto doloremque neque nihil soluta animi quasi qui id aliquid consequatur. Sint laudantium optio itaque neque voluptates! Ex, aspernatur quod deleniti incidunt repellat aliquid repudiandae distinctio ipsum dolor, sit amet consectetur adipisicing elit. Quibusdam quae illum ratione commodi sit tempora voluptatum rerum error, iste numquam placeat est inventore. Molestiae architecto doloremque neque nihil soluta animi q?</p>
            </figcaption>
          </figure>
        </section>
    </main>
</body>