  <body id="black">
    <!----------------- MAIN ---------------------------->
    <main>
      <section class="activities">
        <h1>gym app</h1>
        <section>
          <figure class="flex app">
            <img src="<?= $wwwUrl ?>/img/carroussel3.jpg" alt="" />
            <figcaption>
              <h3>
                bénéficier d'avantages et de réductions !
              </h3>
              <p>
                Lorem ipsum dolor, sit amet consectetur adipisicing elit.
                Quibusdam quae illum ratione commodi sit tempora voluptatum
                rerum error, iste numquam placeat est inventore. Molestiae
                architecto doloremque neque nihil soluta animi quasi qui id
                aliquid consequatur. Sint laudantium optio itaque neque
                voluptates! Ex, aspernatur quod deleniti incidunt repellat
                aliquid repudiandae distinctio ipsum dolor, sit amet consectetur
                adipisicing elit. Quibusdam quae illum ratione commodi sit
                tempora voluptatum rerum error, iste numquam placeat est
                inventore. Molestiae architecto doloremque neque nihil soluta
                animi q?
              </p>
              <div>
                <a href="<?= $wwwUrl ?>#">
                  <img src="<?= $wwwUrl ?>/img/app-appstore.png" alt="" />
                </a>
                <a href="#">
                  <img src="<?= $wwwUrl ?>/img/app-googleplay.png" alt="" />
                </a>
              </div>
            </figcaption>
          </figure>
        </section>
      </section>
    </main>
  </body>
